{% set name = "imodels" %}
{% set version = "2.0.2" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/imodels-{{ version }}.tar.gz
  sha256: 6a96ca1c703fd425e02392e5ae7eacb87a6947d78212d3401e3e64b1f83ccabb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - matplotlib-base
    - mlxtend >=0.18.0
    - numpy
    - pandas
    - requests
    - scipy
    - scikit-learn
    - tqdm

test:
  imports:
    - imodels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/csinva/imodels
  summary: Implementations of various interpretable models
  license: MIT
  license_file: license.md

extra:
  recipe-maintainers:
    - giswqs
