{% set name = "imodels" %}
{% set version = "1.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/imodels-{{ version }}.tar.gz
  sha256: eac7cf9cea9ffd7d8b52be0815359c9778ed076bfb004f147944aa1df3861156

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - matplotlib-base
    - mlxtend >=0.18.0
    - numpy
    - pandas
    - requests
    - scipy
    - scikit-learn
    - tqdm

test:
  imports:
    - imodels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/csinva/imodels
  summary: Implementations of various interpretable models
  license: MIT
  license_file: license.md

extra:
  recipe-maintainers:
    - giswqs
